apiVersion: v1
kind: Service
metadata:
  name: springservice
spec:
  type: NodePort  # Change the type to NodePort
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 8080     # Port exposed externally on the nodes
      targetPort: 8080  # Port your backend service is listening on
      nodePort: 30296
