apiVersion: v1
kind: Service
metadata:
  name: angularrr-service
spec:
  selector:
    app: angular-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32432
